---
abstract: 'Blog plugin for Skryf'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  DDP: '0'
  FindBin: '0'
  List::Util: '0'
  Mojolicious: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Skryf-Plugin-Blog
requires:
  DateTime: '0'
  Hash::Merge: '0'
  Mojo::Base: '0'
version: '1.0'
